services:
  onlineshop-backend:
    image: microservices/onlineshop:0.0.1-SNAPSHOT
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - MX=384m
      - MS=384m
      - META=256m
      - SPRING_PROFILES_ACTIVE=local-docker
      - BBDD_HOST=railway
      - BBDD_PORT=3306
      - BBDD_DATABASE=online_shop
      - BBDD_USERNAME=root
      - BBDD_PASSWORD=afdilNrIKsnqBalHKYVILsyPCqaLLLOj
      - SMTP_USERNAME=proyectoopositaweb@gmail.com
      - SMTP_PASSWORD=ysxv wrhe cqdi pncs
    volumes:
      - onlineshop_images:/app/static/products/images/
    networks:
      - railway_network

volumes:
    onlineshop_images:
        driver: local

networks:
    railway_network:
        external: true